config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :users, only: [] do
    member do
      get :setup_email
      patch :confirm_email
    end
  end

  root to: 'questions#index'

  concern :ratingable do
    member do
      post :like
      post :dislike
      post :cancel
    end
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  resources :questions, except: :edit, concerns: [:ratingable, :commentable] do
    resources :answers,
              only: [:create, :update, :destroy],
              concerns: [:ratingable, :commentable],
              shallow: true do
      member do
        put :set_best
      end
    end

    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: :destroy

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

  resources :search, only: :index
end

app/models/question.rb
class Question < ApplicationRecord
  include Ratingable
  include Commentable
  include Subscribable

  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :attachments, dependent: :destroy, as: :attachable

  validates :title, :body, presence: :true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :find_question, only: :show

  authorize_resource

  def index
    respond_with(Question.all)
  end

  def show
    respond_with(@question, serializer: QuestionShowSerializer)
  end

  def create
    current_user.questions.create(question_params)
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Rated

  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]
  before_action :load_question, only: [:show, :update, :destroy]
  before_action :build_answer, only: :show
  after_action :publish_question, only: [:create]

  authorize_resource

  respond_to :js

  def index
    respond_with(@questions = Question.all)
  end

  def show
    @answers = @question.answers.by_best
    respond_with @question
  end

  def new
    respond_with(@question = current_user.questions.build)
  end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def update
    if current_user.author_of?(@question)
      @question.update(question_params)
      respond_with @question
    end
  end

  def destroy
    respond_with(@question.destroy) if current_user.author_of?(@question)
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def build_answer
    @answer = @question.answers.build
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file, :id, :_destroy])
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast('questions', question: @question)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.slim
div class="question_#{question.id}"
  - cache question do
    p
      h2 = question.title
    p
      h3 = question.body
  p
    = render 'shared/rating', resource: question
  h4 Attachments:
  ul
    - question.attachments.each do |a|
      - cache attachment do
        li id="attachment_#{a.id}"
          => link_to a.file.identifier, a.file.url
      - if can?(:destroy, a)
        = link_to 'Remove file',
                  attachment_path(a),
                  method: :delete,
                  data: { confirm: 'are you sure?', remote: true }

  - if can?(:update, question)
    p = link_to 'Edit question', '', class: 'edit-question-link', data: { question_id: question.id }
    p
      = form_with model: question,
                  id: "edit-question-#{question.id}",
                  class: 'edit_question_form',
                  remote: true do |f|
        = f.label :title
        = f.text_field :title

        = f.label :body
        = f.text_area :body

        = f.submit 'Save'

  - if can?(:create, Subscription)
    - if question.subscribed?(current_user)
      = link_to 'Unsubscribe',
                subscription_path(question.subscribed?(current_user)),
                method: :delete
    - else
      = link_to 'Subscribe',
                question_subscriptions_path(question),
                method: :post

  h4 Comments:
  div class="comment_question_#{question.id}"
    p
      = render question.comments
    p
      = render 'comments/form', resource: question

app/views/questions/index.html.slim
- if can?(:create, Question)
  p = link_to 'Ask question', new_question_path

table
  thead
    tr
      th Questions
      th Show
      th Destroy
  tbody
    - @questions.each do |question|
      tr
        td = question.title
        td = link_to 'Show', question
        - if can?(:destroy, question)
          td = link_to 'Delete',
             question_path(question),
             method: :delete,
             data: { confirm: 'Are you sure?' }

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question, local: true do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_field :body
  p Attachments:
  p
    = f.fields_for :attachments, @question.attachments.build do |a|
      = link_to_add_association 'Add file', f, :attachments, partial: 'shared/attachment_fields'

  p
    = f.submit

app/views/questions/show.html.slim
.question data-id="#{@question.id}"

#flash

#question_errors

= render @question

#answer_errors

.answers
  - if @answers.present?
    = render @answers
  - else
    p There are no answers yet

div -------------------------------------------------------------------------------

- if can?(:create, Answer)
  = form_with model: [@question, @answer], class: 'new_answer_form', remote: true do |f|

    = render 'shared/errors', resource: @answer
    p
      = f.label :body
      = f.text_field :body
    p
      = f.fields_for :attachments, @answer.attachments.build do |a|
        = link_to_add_association 'Add file', f, :attachments, partial: 'shared/attachment_fields'
    p
      = f.submit

app/views/questions/update.js.erb
$('#question_errors').html('');
$('#flash').html('');

<% if @question.errors.present? %>
  $('#question_errors').html('<%= j render "shared/errors", resource: @question %>');
<% else %>
  $('.question_<%= @question.id %>').replaceWith('<%= j render @question %>');
  $('#flash').html("<%= j render 'shared/flash' %>");

  <% flash.clear %>
<% end %>