config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :users, only: [] do
    member do
      get :setup_email
      patch :confirm_email
    end
  end

  root to: 'questions#index'

  concern :ratingable do
    member do
      post :like
      post :dislike
      post :cancel
    end
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  resources :questions, except: :edit, concerns: [:ratingable, :commentable] do
    resources :answers,
              only: [:create, :update, :destroy],
              concerns: [:ratingable, :commentable],
              shallow: true do
      member do
        put :set_best
      end
    end

    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: :destroy

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

  resources :search, only: :index
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Ratingable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user
  has_many :attachments, dependent: :destroy, as: :attachable

  validates :body, presence: :true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  after_commit :subscribers_notification, on: :create

  scope :by_best, -> { order(best: :desc, created_at: :desc) }

  def set_best
    current_best = question.answers.find_by(best: true)

    transaction do
      current_best.update!(best: false) if current_best
      update!(best: true)
    end
  end

  def subscribers_notification
    AnswerNotificationJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Rated

  before_action :authenticate_user!, only: [:create, :update, :destroy, :set_best]
  before_action :load_question, only: [:create]
  before_action :load_answer, only: [:update, :destroy, :set_best]
  after_action :publish_answer, only: [:create]

  authorize_resource

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user

    flash[:notice] = 'Your answer successfully created.' if @answer.save
  end

  def update
    if current_user.author_of?(@answer)
      @answer.update(answer_params)
      flash[:notice] = 'Your answer successfully updated.'
    else
      flash[:alert] = "You can not edit another user's answer!"
      redirect_to @answer.question
    end
  end

  def destroy
    flash[:notice] = 'Your answer successfully deleted.' if @answer.destroy
  end

  def set_best
    if current_user.author_of?(@answer.question)
      @answer.set_best

      flash[:notice] = "Answer set as best successfully."
    else
      flash[:alert] = "You can't set the best answer for another user's question."
    end
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file, :id, :_destroy])
  end

  def publish_answer
    return if @answer.errors.any?

    attachments = @answer.attachments.map do |a|
      { id: a.id, url: a.file.url, name: a.file.identifier }
    end

    ActionCable.server.broadcast("answers_for_question_#{@answer.question_id}",
                                 answer: @answer,
                                 attachments: attachments,
                                 question_user_id: @answer.question.user_id
                               )
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :find_question, only: [:index, :create]
  before_action :find_answer, only: :show

  authorize_resource

  def index
    respond_with(@question.answers)
  end

  def show
    respond_with(@answer, serializer: AnswerShowSerializer)
  end

  def create
    @answer = @question.answers.build(answer_params)
    @answer.user = current_user
    @answer.save
  end

  private

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
div class="answer_#{answer.id}"
  div -------------------------------------------------------------------------------
  p
    - if can?(:set_best, answer) && !answer.best?
      - cache answer do
        = answer.body
      div = link_to 'The best', set_best_answer_path(answer), method: :put, remote: true
    - else
      = answer.body
  p
    = render 'shared/rating', resource: answer

    - if can?(:update, answer)
      p = link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
      = form_with model: answer,
                  id: "edit-answer-#{answer.id}",
                  class: 'edit_answer_form',
                  remote: true do |f|
          = f.label :body, 'Answer'
          = f.text_area :body
          = f.submit 'Save'
      - if can?(:destroy, answer)
        = link_to 'Delete',
                    answer_path(answer),
                    method: :delete,
                    data: { confirm: 'Are you sure?', remote: true }

    ul
      - answer.attachments.each do |a|
        - cache attachment do
          li id="attachment_#{a.id}"
            => link_to a.file.identifier, a.file.url
        - if can?(:destroy, a)
          = link_to 'Remove file',
                    attachment_path(a),
                    method: :delete,
                    data: { confirm: 'are you sure?', remote: true }

    div class="comment_answer_#{answer.id}"
        p
          = render answer.comments
        p
          = render 'comments/form', resource: answer

app/views/answers/create.js.erb
$('#answer_errors').html('');
$('#flash').html('');

<% if @answer.errors.present? %>
  $('#answer_errors').append("<%= j render 'shared/errors', resource: @answer %>");
<% else %>
  $('.answers').append("<%= j render @answer %>");
  $('#flash').append("<%= j render 'shared/flash' %>");

  $('.new_answer_form #answer_body').val('');
  $('.nested-fields').remove();
  <% flash.clear %>
<% end %>

app/views/answers/destroy.js.erb
$('#answer_errors').html('');
$('#flash').html('');

$('.answer_<%= @answer.id %>').remove();
$('#flash').html("<%= j render 'shared/flash' %>");

<% flash.clear %>

app/views/answers/set_best.js.erb
$('#answer_errors').html('');
$('#flash').html('');

$('.answers').html("<%= j render @answer.question.answers.by_best %>");
$('#flash').html("<%= j render 'shared/flash' %>");

<% flash.clear %>

app/views/answers/update.js.erb
$('#answer_errors').html('');
$('#flash').html('');

<% if @answer.errors.present? %>
  $('#answer_errors').html("<%= j render 'shared/errors', resource: @answer %>");
<% else %>
  $('.answer_<%= @answer.id %>').replaceWith("<%= j render @answer %>");
  $('#flash').html("<%= j render 'shared/flash' %>");

  <% flash.clear %>
<% end %>