config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :users, only: [] do
    member do
      get :setup_email
      patch :confirm_email
    end
  end

  root to: 'questions#index'

  concern :ratingable do
    member do
      post :like
      post :dislike
      post :cancel
    end
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  resources :questions, except: :edit, concerns: [:ratingable, :commentable] do
    resources :answers,
              only: [:create, :update, :destroy],
              concerns: [:ratingable, :commentable],
              shallow: true do
      member do
        put :set_best
      end
    end

    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: :destroy

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

  resources :search, only: :index
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Qna
    = Gon::Base.render_data

    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    nav
        div
          p = link_to 'Index page', questions_path
          p = link_to 'Search', search_index_path
          - if user_signed_in?
            => current_user.email
            = link_to 'Log out', destroy_user_session_path, method: :delete
          - else
            => link_to 'Sign in', new_user_session_path
            = link_to 'Sign up', new_user_registration_path
    = render 'shared/flash'
    = yield